export const CHENNAI_DEMO_SCENARIO = {
  name: 'Simulated Cyclone Michaung Inundation - Chennai EOC Exercise',
  disasterType: 'Flood' as const,
  city: 'Chennai',
  description:
    'SIMULATED SCENARIO ONLY (Not Live Government Data): Intense Northeast Monsoon cloudburst and storm surge leading to Adyar river basin overflow and severe waterlogging across southern and central Chennai zones.',
  severity: 'Critical' as const,
  zones: [
    {
      name: 'Velachery Lake Catchment',
      locality: 'Velachery',
      population: 4200,
      severity: 'Critical' as const,
      latitude: 12.9815,
      longitude: 80.2180,
      rainfall: 245.5,
      waterLevel: 1.8,
      roadStatus: 'Inundated',
      injured: 84,
      vulnerablePopulation: 620,
      status: 'Critical' as const,
    },
    {
      name: 'Saidapet Adyar Basin Sector',
      locality: 'Saidapet',
      population: 5100,
      severity: 'Critical' as const,
      latitude: 13.0213,
      longitude: 80.2231,
      rainfall: 260.0,
      waterLevel: 2.3,
      roadStatus: 'Impassable',
      injured: 110,
      vulnerablePopulation: 850,
      status: 'Evacuation Required' as const,
    },
    {
      name: 'T. Nagar Commercial & Residential Hub',
      locality: 'T. Nagar',
      population: 3600,
      severity: 'High' as const,
      latitude: 13.0418,
      longitude: 80.2341,
      rainfall: 180.0,
      waterLevel: 0.9,
      roadStatus: 'Waterlogged',
      injured: 42,
      vulnerablePopulation: 310,
      status: 'Warning' as const,
    },
    {
      name: 'Adyar Estuary & Coastal Belt',
      locality: 'Adyar',
      population: 2800,
      severity: 'Moderate' as const,
      latitude: 13.0012,
      longitude: 80.2565,
      rainfall: 140.0,
      waterLevel: 0.4,
      roadStatus: 'Partially Blocked',
      injured: 18,
      vulnerablePopulation: 190,
      status: 'Monitoring' as const,
    },
    {
      name: 'Tambaram Southern Gateway Sector',
      locality: 'Tambaram',
      population: 2800,
      severity: 'High' as const,
      latitude: 12.9249,
      longitude: 80.1000,
      rainfall: 210.5,
      waterLevel: 1.2,
      roadStatus: 'Waterlogged',
      injured: 66,
      vulnerablePopulation: 430,
      status: 'Warning' as const,
    },
  ],
  resources: {
    rescueVehicles: 10,
    ambulances: 5,
    doctors: 8,
    medicalTeams: 4,
    shelters: 3,
    foodKits: 3000,
    waterSupplies: 5000,
    rescuePersonnel: 50,
  },
};
